name: Crystal CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-24.04

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: shards install --ignore-crystal-version
    - name: Code formatting
      run: crystal tool format --check
    - name: Code inspection with ameba
      run: bin/ameba src
    - name: Run specs
      env:
        DEFAULT_REGION: ap-northeast-1
        AWS_ACCOUNT_ID: "000000000000"
        AWS_ACCESS_KEY_ID: dummy-access-key
        AWS_SECRET_ACCESS_KEY: dummy-secret-key
      run: |
        docker compose up -d
        crystal spec -v
